Table users {
  id guid [not null, primary key]
  nickname text [not null]
  created_at timestamp [not null]
}

Table files {
  id guid [not null, primary key]
  post_id guid [not null]
  bucket text [not null]
  resource text [not null]
  filename text [not null]
}

Table posts {
  id guid [not null, primary key]
  title varchar [not null]
  content text [not null]
  author_id integer [not null]
  geo GEOGRAPHY(Point) [not null]
  created_at timestamp [not null]
}

Table comments {
  id guid [not null, primary key]
  index_in_post integer [not null]
  post_id guid [not null]
  author_id guid [not null]
  content varchar [not null]
  created_at timestamp [not null]
}

Table follows {
  following_user_id guid [not null]
  followed_user_id guid [not null]
  created_at timestamp [not null]
}

Ref: posts.author_id > users.id
Ref: follows.following_user_id > users.id
Ref: follows.followed_user_id > users.id
Ref: comments.author_id > users.id
Ref: comments.post_id > posts.id
Ref: files.post_id > posts.id